version: "2"
services:
  web:
    image: python:3
    volumes:
      - ./web:/app/src
    env_file: web.env
    expose:
      - "80"
    working_dir: /app/src
    command: python3 -m http.server --bind 0.0.0.0 80
    networks:
      - nginx
networks:
  nginx:
    external: true
